repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args:
          - --rcfile
          - .pylintrc
      - id: black
        name: black
        entry: black
        always_run: true
        language: python
        args:
          - -v
        language_version: python3.8
