version: "3.8"

volumes:
    static:
    media:

services:
  api:
    restart: unless-stopped
    image: extraction_services_api
    build:
      context: ../
      dockerfile: deploy/Dockerfile.server
    env_file:
      - .env
    ports:
      - "80:8000"
    command: ../entrypoint.sh
    volumes:
      - ../src:/app

  qcluster:
    image: extraction_services_qcluster
    network_mode: "host"
    build:
      context: ../
      dockerfile: deploy/Dockerfile.worker
    env_file:
      - .env
    command: python manage.py qcluster
