FROM mcr.microsoft.com/playwright/python:v1.22.0-focal

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1


# Requirements are installed here to ensure they will be cached.
COPY ./requirements /requirements
RUN pip install -r /requirements/dev.txt
RUN playwright install

ADD ./src /app


WORKDIR /app

ENV DJANGO_SETTINGS_MODULE 'services.settings.dev'
