# Generated by Django 3.2.13 on 2022-07-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='secondary_error',
            field=models.BooleanField(default=False),
        ),
    ]
