# Generated by Django 2.2.16 on 2022-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0002_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
