# Generated by Django 3.2.13 on 2022-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0003_houseauction_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseauction',
            name='is_sold',
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='auction_datetime',
            field=models.DateTimeField(),
        ),
    ]
