# Generated by Django 3.2.13 on 2022-08-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0005_loggermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggermodel',
            old_name='level',
            new_name='level_name',
        ),
    ]
