# Generated by Django 2.2.16 on 2022-05-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0005_auto_20220521_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorreport',
            name='path',
        ),
        migrations.AddField(
            model_name='errorreport',
            name='trace_back',
            field=models.TextField(blank=True, null=True),
        ),
    ]
