# Generated by Django 2.2.16 on 2022-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0006_auto_20220521_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseauction',
            old_name='auction_hour',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='houseauction',
            name='domain',
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='auction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseauction',
            name='property_link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
