# Generated by Django 2.2.16 on 2022-05-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0007_auto_20220521_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseauction',
            old_name='auction_date',
            new_name='auction_datetime',
        ),
    ]
