# Generated by Django 3.2.13 on 2022-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0009_houseauction_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
