# Generated by Django 3.2.13 on 2022-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction_services', '0011_alter_errorreport_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseauction',
            name='number_of_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
